#!/bin/sh

echo "write you want to be readed ><"
read text

echo "$text" | tr -d '\n' | sed -e '2,$s/\./ /g' | \
  piper --model en_US-libritts-high.onnx --output-raw | \
  aplay -r 22050 -f S16_LE -t raw - >/dev/null
